# Generated by Django 4.1.1 on 2024-10-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_rename_f_fabricacion2_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='Medico General', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='lab_ciudad',
            field=models.CharField(default='Santiago', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='lab_pais',
            field=models.CharField(default='Chile', max_length=255),
        ),
    ]
