# Generated by Django 4.1.1 on 2024-10-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_directorgeneral_especialidad_laboratorio_lab_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='id',
            new_name='lab_id',
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='nombre',
            new_name='lab_nombre',
        ),
    ]
