# Generated by Django 5.1.1 on 2024-10-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_rename_id_laboratorio_lab_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoLaboratorio',
        ),
    ]
